version: '3'

services:
  roadrunner:
    build:
      context: ./roadrunner
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - ./:/app
      - ./roadrunner/.rr.yaml:/etc/rr.yaml:ro